name: Execute SS Node Extractor
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Execute SS_Node_Extractor.spec
      run: |
        set -e
        # 替换下面的命令为实际运行SS_Node_Extractor.spec的命令
        SS_Node_Extractor.spec
